version: '3.0'

services:
  loki:
    image: grafana/loki:2.8.5
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/datasources
